### ISSUE TITLE
[Question] install not working on windows

### ISSUE THREAD

**Issue by quasiperfect** [wponion/wponion#100]
## Describe the bug
the installation instructions don't work on windows

## To Reproduce
1. install wordpress
2. go to wp-content\themes\twentynineteen and run composer require wponion/wponion
3. edit functions.php and add require get_template_directory() . '/vendor/autoload.php';
4 test using the example form the "Usage {If Downloaded Manually}" section
add to functions.php
add_action('wponion_loaded','my_after_wponion_loaded');

function my_after_wponion_loaded(){
die('test');
}
5 try the plugin download the plugin from https://github.com/wponion/demo
extract to plugin folder and activate. nothing new in wp admin

## Expected behavior
in step 4 i expect to see 'test' on the screen and nothing more
in step 5 i expect to see some new menu in or something

i get no error in php and wordpress works fine just no sign of wponion

**Comment by varunsridharan** [comment]
@quasiperfect WPOnion will not work if its loaded inside a theme. but wponion can create settings page for themes/plugins

if you are submitting your theme to wordpress.org i would recommend you use 
http://tgmpluginactivation.com/ and directly install WPOnion from [wordpress.org as a plugin](https://wordpress.org/plugins/wponion/)

if you are submitting your theme to marketplaces like themeforest.net or somewhere else
i would recommend you to either use http://tgmpluginactivation.com/  or prepack with your theme's core plugin.

if you are using it for your personal development / client work
then just install directly from wordpress.org.

**Comment by quasiperfect** [comment]
@varunsridharan i was trying to test on localhost and i just followed the instructions from the site and documentation.

**Comment by varunsridharan** [comment]
sorry about that. we did had support to load wponion via theme. but after we changed as we decided to follow wordpress standards. and i am still working on docs which well be updating soon. !
