### ISSUE TITLE
How to forbidden wordpress url exchange `&` to `#038;`?

### ISSUE THREAD

**Issue by kkotha82** [wponion/wponion#161]
I want to pass some value through url in wordpress, but I met some trouble that wordpress will exchange & to #038; automatically, how to make a & still as a & ?

I noticed in wp-includes/formatting.php, there has many rules to exchange symbols, I tried modify some code, but failed.

some link like

site.com?this=that&that=this will output to the web browser address like site.com?this=that#038that=this

and the page can not get the value in the part that=this

how to setting correctly? thanks.

**Comment by varunsridharan** [comment]
Fix pushed to `development` branch soon it will be released in stable.
