### ISSUE TITLE
Save Settings button not showing

### ISSUE THREAD

**Issue by kkotha82** [wponion/wponion#162]
## Describe the bug
Save settings button is not showing when moving from a tab which does not have any fields to another tab which has fields

## To Reproduce
1. Create a settings page with 3 containers
2. Have fields in container 1 and container 2
3. No fields in container 3
4. When container 3 is opened, the save settings button is hidden
5. BUG: When container 1 or 2 is opened, the button remains hidden

## Expected behavior
In step 5 above, the save settings button should be showing

**Comment by varunsridharan** [comment]
fixed and updated in development branch soon  will be pushed to stable.
