### ISSUE TITLE
[Feature Request] Browser Tab Title Fallbacks

### ISSUE THREAD

**Issue by EnterpriseBranding** [wponion/wponion#228]
## Is your feature request related to a problem? Please describe.

Kind of...

When the param `page_title` is not used in the `$menu_settings` array, the browser page title is also removed. Can we set a default for the browser tab to show the`menu_title` based on the following priorities?

## Describe the solution you'd like

If `page_title` is not set
Then check for `framework_title`
If `framework_title` is not set
Then show `menu_title`
As the "Browser Title"

## Describe alternatives you've considered

N/A

## Additional context
![‹ My Great Blog — WordPress-04-27-20-zxs4v](https://user-images.githubusercontent.com/6123260/80377544-6a9f7480-8869-11ea-9f60-1d267579bf1f.png)

**Comment by varunsridharan** [comment]
Released in V 1.5.3
