### ISSUE TITLE
[BUG] 'theme' arg in Taxonomy Module produces error if theme is not "wp_modern"

### ISSUE THREAD

**Issue by EnterpriseBranding** [wponion/wponion#233]
## Describe the bug
If `'theme' => 'wp'` or `'theme' => 'wc'` are used in the [taxonomy module](https://github.com/wponion/wponion/blob/221b2bca87aaa2883b2672df7db4a11884ad1e59/core/helpers/modules/taxonomy.php) the output has errors. 

See screenshot.

## To Reproduce
Set demo code as below...

![image](https://user-images.githubusercontent.com/6123260/80803958-c3c91a00-8b81-11ea-8cf0-9ce5902ca531.png)

Then go to post "category". It has an error instead of field output. It does this if `'theme' => 'wc'` too.

## Expected behavior
Should not be I think. Please clarify. Thanks!

## Screenshots
Error output is..

![image](https://user-images.githubusercontent.com/6123260/80804029-ec511400-8b81-11ea-8661-7c9b4724ef61.png)

## Sample Codes
N/A

## Additional context
N/A

**Comment by varunsridharan** [comment]
Fixed in V 1.5
