### ISSUE TITLE
Option to hide label per single field

### ISSUE THREAD

**Issue by EnterpriseBranding** [wponion/wponion#26]
This is a feature request to add an option to hide the label per single field.

As of now, when title value is `false` or `null` the field will be displayed in full width.

It would be useful to have the option to hide the title when needed, even stand alone places.

**Comment by varunsridharan** [comment]
Feature Added in Development Version.

**Comment by EnterpriseBranding** [comment]
@varunsridharan ok Awesome!

Thanks! Much Appreciated!

**Comment by varunsridharan** [comment]
Released In V0.0.9.6

**Comment by EnterpriseBranding** [comment]
Great! Sounds GOOD <3
