### ISSUE TITLE
Javascript Dependency Rules

### ISSUE THREAD

**Issue by varunsridharan** [wponion/wponion#28]
More Javascript Dependency Rules will be handy

1. [x] Option to check if a field is empty 
2. [x] option to check if a field contains a word / char (`strpos` --php some thing for JS)

**Comment by EnterpriseBranding** [comment]
+1

**Comment by varunsridharan** [comment]
Added in V 0.0.10.3 https://github.com/wponion/wponion/releases/tag/0.0.10.3
