### ISSUE TITLE
CPT and Taxonomy Support (Module with Order Sorting)

### ISSUE THREAD

**Issue by EnterpriseBranding** [wponion/wponion#31]
## Is your feature request related to a problem? Please describe.

No.

## Describe the solution you'd like

Custom Post Type and Custom Taxonomy Support (WPOnion Module)

## Additional context

This is a request for Custom Post Type and Custom Taxonomy Support as WPOnion Module (with built-in option to sort the created custom post type, or taxonomy, or both, and for hierarchical sorting as well)

I think this is useful and you can probably see why, for option pages have their WPO Options, and custom post type and taxonomies have their WPO Metaboxes. So to having sorting abilities built-in for those custom post types and taxonomies is very useful.

But I wanted to add this built-in sorting feature as well to the CPT and Taxo support. I think will be great for WPO.

The feature is a lightweight option to sort the custom post types and taxonomies created with WPO. Something like `'sortable' => TRUE`. Then the created post type or taxonomy would be sortable in the Wordpress backend.

I have a very light weight script created by [Remi Corson - Website](https://remicorson.com/about-me/) / @corsonr. It was released on Codecanyon many years ago and many years ago it was removed, but still works wonderfully. 

[Here is that plugin to reference](https://my.pcloud.com/publink/show?code=XZQaTI7ZBSu7wz1VqfpD0POjAvxDEkV60gjV).

As a screenshot visual to reference here is one from [Post Types Order](https://my.pcloud.com/publink/show?code=XZQaTI7ZBSu7wz1VqfpD0POjAvxDEkV60gjV).

But I think the option to sort hierarchal orders is important, which neither of these offer in the native Wordpress list.

Screenshot:

![image](https://user-images.githubusercontent.com/6123260/58035419-b775b980-7af6-11e9-95bd-2ecb11a4119a.png)

**Comment by varunsridharan** [comment]
@all-contributors please add @EnterpriseBranding doc

**Comment by varunsridharan** [comment]
@all-contributors please add @EnterpriseBranding doc,ideas

**Comment by varunsridharan** [comment]
@all-contributors please add @EnterpriseBranding ideas
