### ISSUE TITLE
Drag and Drop group elements would be nice!

### ISSUE THREAD

**Issue by devmybest** [wponion/wponion#5]
The framework is pretty great with lot of modules. Thanks a lot for the awesome plugin.

It would be nice to have a drag and drop group of elements (defined by developer) with a sorter to the framework. 
So the user can fill details in to the dropped inputs and sort the groups as he wants and save it.
For example, 
1. Drag group 1 (text field and checkboxes)
2. Drag group 2 (textarea field and select boxes)
etc.

Hope this will be helpful for all.

**Comment by varunsridharan** [comment]
Request Rejected . as its not required by large user base.
