### ISSUE TITLE
[Feature Request] A fresher color picker replacement!

### ISSUE THREAD

**Issue by EnterpriseBranding** [wponion/wponion#77]
## Is your feature request related to a problem? Please describe.
No.

## Describe the solution you'd like
I think it would be nice to replace the current normal stand color picker with this one 
@ https://simonwep.github.io/pickr/
@ https://github.com/Simonwep/pickr

## Describe alternatives you've considered
N/A

## Additional context
N/A

Thoughts?

**Comment by varunsridharan** [comment]
@EnterpriseBranding thanks :-) now this library is used in wponion instead of default WordPress Color Picker Library.

**Comment by EnterpriseBranding** [comment]
AWESOME!!! THIS IS GREAT!!!

THANKS FOR THE UPDATE!!!

![ezgif-3-9d59b0c771bf](https://user-images.githubusercontent.com/6123260/61386872-0afc4d80-a883-11e9-81d4-f30772f2f073.gif)
